permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
mathjax: disabled
sass:
  style: compressed

# 作者信息
author:
  name: Rico Ly
  email: rico_ly@163.com


# 站点信息
title: Rico Ly's blog
description: Awesomeness & Legendery
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: /assets/image/logo.jpg
favicon: /assets/image/logo.jpg



# Jekyll Plugin
# https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
gems:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed


# disqus 设置
disqus:
  shortname: suyan-zh

categories: Golang Raft Python Database Docker Tool CheatSheet



