permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
mathjax: disabled
sass:
  style: compressed

# 作者信息
author:
  name: Eric Zhou
  email: dejavuzhou@qq.com
  link: http://captcha.mojotv.cn
  weibo: http://weibo.com/u/2706451481?is_all=1
  github: http://github.com/dejavuzhou

# 站点信息
title: Eric Zhou's blog
description: Awesomeness & Legendery
url: https://mojotv.cn
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: /assets/image/logo.jpg
favicon: /assets/image/logo.jpg



# Jekyll Plugin
# https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
gems:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed


# disqus 设置
disqus:
  shortname: suyan-zh

categories: Golang Raft Python Database Docker Tool

exclude: util config

ga:
  id: UA-129013660-1
  url: mojotv.cn
